export const DATA_VIEWS = [
  { id: "transactions", label: "Transactions" },
  { id: "all", label: "All" },
  { id: "workflow", label: "Workflow" },
  { id: "user_input", label: "User Input" },
  { id: "llm", label: "LLM" },
  { id: "output", label: "Output" },
  { id: "tools", label: "Tools" },
  { id: "errors", label: "Errors" },
];

export const TRACE_FILTERS = [
  { id: "all", label: "All" },
  { id: "workflow", label: "Workflow" },
  { id: "user_input", label: "User Input" },
  { id: "llm", label: "LLM" },
  { id: "output", label: "Output" },
  { id: "tools", label: "Tools" },
  { id: "errors", label: "Errors" },
];

export const EVENT_LABELS = {
  run_start: "Run Started",
  run_end: "Run Completed",
  step_start: "Step Started",
  step_end: "Step Completed",
  llm_call_start: "LLM Call Started",
  llm_call_end: "LLM Call Completed",
  tool_call_start: "Tool Call Started",
  tool_call_end: "Tool Call Completed",
  tool_call_error: "Tool Call Error",
  run_error: "Run Error",
};

export const EMPTY_AGENT_FORM = {
  display_name: "",
  agent_code: "",
  agent_description: "",
  agent_type: "",
  use_case_summary: "",
  business_objective: "",
  lifecycle_status: "Draft",
  base_url: "https://hipaa.cloud.langfuse.com",
  public_key: "",
  secret_key: "",
  primary_node_id: "",
  supporting_node_ids: [],
  placement_type: "Primary",
  business_function: "",
  process_area: "",
  department_owner: "",
  business_owner: "",
  technical_owner: "",
  operational_support_owner: "",
  escalation_contact: "",
  support_team: "",
  capability_type: "",
  input_types: [],
  output_types: [],
  actions_performed: "",
  external_tools_used: "",
  apis_used: "",
  connected_systems: "",
  data_sources: "",
  data_classification: "",
  pii_usage: false,
  sensitive_data_usage: false,
  read_access_systems: "",
  write_access_systems: "",
  access_scope: "",
  business_criticality: "Medium",
  process_dependency: "Supporting",
  user_impact: "Internal Only",
  failure_impact: "Operational Delay",
  downtime_tolerance: "8-24 Hours",
  autonomy_level: "Human Approval Required",
  risk_level: "Medium",
  human_approval_required: true,
  approval_required_before_execution: true,
  audit_logging_required: true,
  monitoring_required: true,
  escalation_required: false,
  fallback_process_available: false,
  compliance_policy_reference: "",
  regulatory_impact: "",
  audit_requirement: "",
  deployment_environment: "Development",
  deployment_status: "Draft",
  monitoring_sla: "",
  support_sla: "",
  incident_severity_level: "",
  runtime_dependencies: "",
  linked_infrastructure: "",
  linked_models: "",
};
